apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: starter-devops
spec:
  type: NodePort # Exposes the service on an internal IP in the cluster
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32000
  selector:
    app: postgres
