---
- name: Директория для ключей GPG
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Скачивание GPG ключа Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Добавление репозитория docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  
- name: Установка Docker Engine
  ansible.builtin.apt:
    name: "{{ container_tools_docker_packages }}"
    state: present
    update_cache: yes

- name: Добавление ansible в группу docker
  ansible.builtin.user: 
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Проверка enabled Docker 
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes